export function extractYoutubeVideoId(url: string): string {
  const match = url.match(/(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))([\w-]{11})/);
  return match ? match[1] : '';
}

export async function fetchFullYoutubeTranscript(videoUrl: string): Promise<string | null> {
  const videoId = extractYoutubeVideoId(videoUrl);
  if (!videoId) return null;

  try {
    const pageRes = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7'
      }
    });

    const html = await pageRes.text();

    // Extract ytInitialPlayerResponse
    const playerResponseMatch = html.match(/ytInitialPlayerResponse\s*=\s*({.+?});/);
    if (!playerResponseMatch) return null;

    const playerResponse = JSON.parse(playerResponseMatch[1]);
    const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

    if (!captionTracks || !Array.isArray(captionTracks) || captionTracks.length === 0) {
      return null;
    }

    // Prefer German track ('de'), then German autogenerated, then first track
    let targetTrack = captionTracks.find((t: any) => t.languageCode === 'de');
    if (!targetTrack) {
      targetTrack = captionTracks.find((t: any) => t.vssId?.includes('de'));
    }
    if (!targetTrack) {
      targetTrack = captionTracks[0];
    }

    if (!targetTrack || !targetTrack.baseUrl) return null;

    // Fetch caption XML from YouTube timedtext
    const xmlRes = await fetch(targetTrack.baseUrl);
    const xmlText = await xmlRes.text();

    // Parse <text ...>content</text> tags
    const matches = Array.from(xmlText.matchAll(/<text[^>]*>(.*?)<\/text>/g));
    const lines = matches
      .map(m => decodeXmlText(m[1]))
      .filter(line => line.length > 0);

    if (lines.length === 0) return null;

    // Join lines into full transcript paragraphs
    const fullTranscript = lines.join(' ')
      .replace(/&amp;/g, '&')
      .replace(/&#39;/g, "'")
      .replace(/&quot;/g, '"')
      .replace(/\s+/g, ' ');

    // Group into readable paragraphs of ~400 characters
    const words = fullTranscript.split(' ');
    const paragraphs: string[] = [];
    let currentP: string[] = [];

    words.forEach(w => {
      currentP.push(w);
      if (currentP.join(' ').length >= 350 && /[.!?]$/.test(w)) {
        paragraphs.push(currentP.join(' '));
        currentP = [];
      }
    });
    if (currentP.length > 0) paragraphs.push(currentP.join(' '));

    return paragraphs.join('\n\n');
  } catch (err) {
    console.warn('Direct YouTube transcript fetch warning:', err);
    return null;
  }
}

function decodeXmlText(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/<[^>]*>/g, '') // remove HTML tags
    .trim();
}
